services:
  rover-kinematics:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
      args:
        SSH_PORT: 2123
    image: rover-kinematics
    container_name: rover-kinematics
    hostname: rover-kinematics
    extra_hosts:
      - "rover-kinematics=127.0.0.1"
    stdin_open: true
    tty: true
    pid: "host"
    ipc: "host"
    init: true
    network_mode: "host"
    privileged: true
    environment:
      - TZ=Europe/Warsaw
      - ROS_ENABLE_AUTOSTART=1
      - ROS_BUILD_ON_STARTUP=on-failure
    volumes:
      - type: bind
        source: ./
        target: /mnt/local
        bind:
          create_host_path: false
      - type: bind
        source: ./.devcontainer/rex
        target: /etc/init.d/rex
        bind:
          create_host_path: false
      - type: bind
        source: "${REX_CONTAINER_AUTHORIZED_KEYS:-/dev/null}"
        target: /run/secrets/authorized_keys
        read_only: true # Make sure this stays read-only!
        bind:
          create_host_path: false
    restart: unless-stopped
